# Generated by Django 4.2.20 on 2025-04-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stat_method',
            field=models.CharField(choices=[('roll', 'Rolled (4d6 drop lowest)'), ('standard', 'Standard Array')], default='roll', max_length=10),
        ),
    ]
