# Generated by Django 4.2.20 on 2025-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargen', '0002_character_stat_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='stat_method',
            field=models.CharField(choices=[('roll', 'Roll (4d6 drop lowest)'), ('standard', 'Standard Array (15,14,13,12,10,8)')], default='roll', max_length=10),
        ),
    ]
